//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_detail
    {
        public string ID { get; set; }
        public string StoreID { get; set; }
        public string AssetClassifyID { get; set; }
        public string AssetFullName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> QuantityOriginalStock { get; set; }
        public Nullable<int> QuantityUsed { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<int> QuantityDestroyed { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string TicketID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Unit { get; set; }
        public string Description { get; set; }
    
        public virtual asset_classify asset_classify { get; set; }
        public virtual request_ticket_history request_ticket_history { get; set; }
        public virtual store_Identifie store_Identifie { get; set; }
    }
}
