//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_allocation_history
    {
        public string ID { get; set; }
        public string AssetID { get; set; }
        public string AllocationFor { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string AllocationBy { get; set; }
        public string RequestBy { get; set; }
        public string LocalStep { get; set; }
        public Nullable<bool> isApprove { get; set; }
        public Nullable<bool> IsReject { get; set; }
    
        public virtual asset_detail asset_detail { get; set; }
        public virtual rank rank { get; set; }
    }
}
