//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_detail
    {
        public string ID { get; set; }
        public string AssetClassifyID { get; set; }
        public string AssetFullName { get; set; }
        public string SupplierID { get; set; }
        public string InvoiceID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
