//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice()
        {
            this.invoice_detail = new HashSet<invoice_detail>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatorID { get; set; }
        public string TicketID { get; set; }
        public string StoreID { get; set; }
        public Nullable<bool> IsReject { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_detail> invoice_detail { get; set; }
        public virtual request_ticket_history request_ticket_history { get; set; }
        public virtual store_Identifie store_Identifie { get; set; }
    }
}
