//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessStep
    {
        public string ID { get; set; }
        public string ProcessID { get; set; }
        public string ParentID { get; set; }
        public string UserID { get; set; }
        public string Approvers { get; set; }
        public Nullable<int> ExpiredTime { get; set; }
        public Nullable<bool> IsUseExpiredTime { get; set; }
        public string Description { get; set; }
        public string StepName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Process Process { get; set; }
    }
}
