//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public string ID { get; set; }
        public string OrganizationalID { get; set; }
        public string ParentStepID { get; set; }
    
        public virtual Organizational Organizational { get; set; }
    }
}
