//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_ticket_history
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request_ticket_history()
        {
            this.invoices = new HashSet<invoice>();
            this.voting_history = new HashSet<voting_history>();
        }
    
        public string ID { get; set; }
        public string RequestBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string StepID { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string Description { get; set; }
        public string ProcessID { get; set; }
        public string RequestType { get; set; }
        public Nullable<bool> IsReject { get; set; }
        public string StoreID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<voting_history> voting_history { get; set; }
    }
}
