//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_function
    {
        public string ID { get; set; }
        public string RoleID { get; set; }
        public string FunctionID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserID { get; set; }
    
        public virtual function function { get; set; }
        public virtual role role { get; set; }
        public virtual user_identifie user_identifie { get; set; }
    }
}
