//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_log
    {
        public string ID { get; set; }
        public string MessageID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Creator { get; set; }
        public string Detail { get; set; }
    
        public virtual message_list message_list { get; set; }
        public virtual user_identifie user_identifie { get; set; }
    }
}
