//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class usage_history
    {
        public string ID { get; set; }
        public string TicketID { get; set; }
        public string AssetID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string UsageFor { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<bool> IsRecovery { get; set; }
        public Nullable<bool> IsLiquidation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
