//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.BUS.DBConnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class voting_history
    {
        public string ID { get; set; }
        public string TicketID { get; set; }
        public string Description { get; set; }
        public string Actor { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Action { get; set; }
        public string StepID { get; set; }
    
        public virtual request_ticket_history request_ticket_history { get; set; }
    }
}
