export const ERROR_API = "base/error_api"
export const LOGIN = "base/login"
export const GET_TOKEN = "base/get_token"
export const SAVE_USER_LOGIN = "base/save_user_login"
export const SAVE_TOKEN = "base/save_token"
export const SET_TAB_LOGIN = "base/set_tab_login"
export const SIGNUP = "base/signup"
export const COOKIE = "base/cookie"
export const GET_USER_INFO = "base/get_user_info"
export const SAVE_USER_INFO = "base/save_user_info"
export const SHOW_MENU = "base/show_menu"

